apiVersion: v1
kind: Service
metadata:
  name: visitors-backend-service
  labels:
    app: visitors
    tier: backend
spec:
  type: clusterIP
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app: visitors
    tier: backend
